# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  another_build:
    runs-on: ubuntu-latest
    steps:
     - name: hello
       run: echo hello
  # add_label:
  #   permissions:
  #     checks: read
  #     pull-requests: write
  #   needs: another_build
  #   uses: ./.github/workflows/blank.yml

            
