# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request_review:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      checks: read
      pull-requests: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/github-script@v6
        with:
          script: |
            
            const owner = "michelle-yooh"
            const repo = "test"
            const pr = context.payload.pull_request
            console.log("----------------------")
            console.log(pr._links.commits)
            console.log("----------------------")
            const pull_number = pr.number

            let reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number,
            })
            let isApproved = true
            for (const review of reviews.data) {
              isApproved = isApproved && (review.state === "APPROVED")
            }
            const commits = await github.rest.pulls.listCommits({
              owner,
              repo,
              pull_number,
            })
            console.log("----------------------")
            console.log(commits)
            console.log("----------------------")
            const lastCommitSha = commits.data.slice(-1)[0].sha
            console.log("----------------------")
            console.log(lastCommitSha)
            console.log("----------------------")
            
            const checkRuns = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: lastCommitSha,
            })
            let allPassed = true
            console.log("----------------------")
            console.log(checkRuns)
            console.log("----------------------")
            for (const checkRun of checkRuns.data.check_runs) {
              console.log("----------------------")
              console.log(checkRun)
              console.log("----------------------")
              if (checkRun.name === "build") {
                continue
              }
              allPassed = allPassed && (checkRun.conclusion === "success")
            }
            
            if (isApproved && allPassed) {
              await github.rest.issues.addLabels({
                issue_number: pull_number,
                labels: ["pull ready"],
                owner,
                repo,
              })
            }
  another_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            asdf

            
